language: ruby
rvm: 2.1.2
before_install:
  - echo 'BEFORE INSTALL START'
  - gem install bundler
  - echo 'BEFORE INSTALL END'
install: gem update --system
install: gem update
install: gem install httparty